apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.remoteKey }}
