apiVersion: v1
kind: Service
metadata:
  name: nepalstay
  namespace: {{ .Release.Namespace }}
  labels:
    app: nepalstay

spec:
  selector:
    app: nepalstay
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  type: ClusterIP
