# this helps to talk to Aws
# this will become identity bridge


apiVersion: v1
kind: ServiceAccount
metadata:
  name: nepalstay
  namespace: nepalstay
  labels:
    app.kubernetes.io/name: nepalstay
  