name: Security Scan
on:
  pull_request: # This event triggers the workflow when a pull request is opened, synchronized (updated), or reopened. It allows the workflow to run security scans on the code changes proposed in the pull request.
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
permissions:
  contents: read
  security-events: write # This permission is required to create security alerts in the repository. It allows the workflow to report any security issues it finds during the scan.

jobs:
  security:
    name: Dependency Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs # This specifies that the scan should be performed on the filesystem of the repository. It checks for vulnerabilities in the files and directories of the codebase.
          scan-ref: . # This specifies the reference point for the scan. In this case, it is set to the current directory (.) of the repository, meaning that the scan will be performed on the entire codebase.
          format: sarif # This specifies that the output format of the scan results should be in SARIF (Static Analysis Results Interchange Format). SARIF is a standardized format for representing static analysis results, which can be consumed by various tools and platforms.
          severity: CRITICAL,HIGH # This specifies the severity levels of vulnerabilities to be reported in the scan results. In this case, only vulnerabilities with CRITICAL, HIGH severity will be included in the output.
          ignore-unfixed: true # This tells Trivy to ignore vulnerabilities that have not been fixed.
          exit-code: 1 # This specifies the exit code that Trivy should return if vulnerabilities are found. An exit code of 1 indicates that vulnerabilities were detected, which can be used to fail the workflow step and alert the developers.
          output: trivy-results.sarif # This specifies the name of the file where the scan results will be saved. The results will be stored in a file named "trivy-results.sarif" in the root directory of the repository.

      - name: Upload Trivy Results
        if: always() && steps.trivy-scan.outcome != 'cancelled' # This condition ensures that the upload step is executed regardless of the outcome of the Trivy scan step, as long as it was not cancelled. It allows the workflow to upload the results even if vulnerabilities were found or if the scan failed.
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif # This specifies the path to the SARIF file generated by the Trivy scan. The upload-sarif action will take this file and upload it to GitHub, where it can be viewed in the Security tab of the repository.
