name: Terraform

on:
    pull_request:
        paths:
            - "terraform/**"
    push:
        branches:
            - main
        paths:
            - "terraform/**"

permissions:
    contents: read
    id-token: write

concurrency:
    group: terraform-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    terraform:
        runs-on: ubuntu-latest
        env:
            TF_VAR_aws_region: us-east-1

        defaults:
            run:
                working-directory: terraform/environments/dev
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4

            - name: Terraform Format
              run: terraform fmt -check -recursive ../../

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                role-session-name: terraform-${{ github.run_id }}
                aws-region: us-east-1
                role-skip-session-tagging: true

            - name: Terraform Init
              run: terraform init -lock-timeout=5m

            - name: Terraform Validate
              run: terraform validate

            - name: Terraform Plan
              run: terraform plan -lock-timeout=5m
